### ISSUE TITLE
Eval dataset

### ISSUE THREAD

**Issue by aliman80** [UAVVaste/UAVVaste#5]
Hi do you have evaluation dataset too if you can please share . Regards

**Comment by MatPiech** [comment]
Hi, sorry for the long delay in response. The dataset doesn't contain any additional test data. Train, validation, and test subsets were separated from 772 images. 
Recently, I added dataset [distribution_file](https://github.com/UAVVaste/UAVVaste/blob/main/annotations/train_val_test_distribution_file.json) that contains an official images split between subsets.
